# TUBES ML
13515055 | Rizky Faramita  
13515064 | Tasya  
13515140 | Francisco Kenandi Cahyono  

# Data Handling

In [1]:
from sklearn import datasets
iris = datasets.load_iris().data

print(iris)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

# Public Library & Importing Libraries

In [12]:
from sklearn.metrics.pairwise import euclidean_distances,manhattan_distances
import numpy as np

def calculateEucledianDistance(data):
    return euclidean_distances(data)

def calculateManhattanDistance(data):
    return manhattan_distances(data)

def eucledianDistance(a,b):
    dist = 0
    for i in range(len(a)):
        dist += np.power((a[i]-b[i]),2)
    return np.sqrt(dist)

def manhattanDistance(a,b):
    dist = 0
    for i in range(len(a)):
        dist += abs(a[i]-b[i])
    return dist

def checkWithScikit(customLabel,scikitLabel):
    if len(customLabel) == len(scikitLabel):
        same = True
        for i in range(len(customLabel)):
            if (customLabel[i] != scikitLabel[i]):
                print("NAY")
                same = False
                break
        if same: 
            print("YAY")
    else:
        print("NAY")

# K-MEANS

K-Means merupakan salah satu metode *clustering* yang sensitif terhadap nilai inisialisasi. Pada metode ini, banyaknya kluster yang ingin dibuat sudah diketahui sejak awal.

Pada dasarnya, akan diinisialisasi sentroid awal untuk masing-masing kluster. Kemudian, dihitung jarak dari setiap data ke setiap sentroid yang ada. Data tersebut akan dimasukkan ke dalam suatu klulster yang sentroidnya paling dekat dengan data.
Kemudian, akan dihitung kembali sentroid setiap kluster dengan cara menghitung *mean*-nya.

Langkah di atas akan diulang secara terus-menerus sehingga tidak terjadi perubahan sentroid ketika perhitungan *mean*.

Pseudocode:
1. Masukkan banyak kluster yang ingin dibuat dan pilih sentroid awal untuk masing-masing kluster.
2. Ulangi: Masukkan (ulang) setiap data ke dalam kluster terdekat, kemudian *update* sentroid setiap kluster dengan cara menghitung *means*-nya.
3. Berhenti ketika sentroid dari setiap kluster tidak ada yang berubah.

Kompleksitas dari algoritma K-Means adalah O(nkt) dengan t adalah jumlah iterasi, k adalah banyaknya kluster, dan n adalah banyaknya data yang ingin dikluster.

### Source Code:

In [ ]:
from numpy import *  
import time  
import matplotlib.pyplot as plt  
  
# calculate Euclidean distance  
def euclDistance(vector1, vector2):  
    return sqrt(sum(power(vector2 - vector1, 2)))
  
# init centroids with random samples  
def initCentroids(dataSet, k):  
    numSamples, dim = dataSet.shape
    centroids = zeros((k, dim))
    for i in range(k):  
        index = int(random.uniform(0, numSamples))
        centroids[i, :] = dataSet[index, :]  
    return centroids  
  
# k-means cluster
def kmeans(dataSet, k):  
    numSamples = dataSet.shape[0]
    clusterAssment = mat(zeros((numSamples, 2)))
    clusterChanged = True  
  
    ## step 1: init centroids  
    centroids = initCentroids(dataSet, k)
  
    while clusterChanged:  
        clusterChanged = False  
        ## for each sample  
        for i in range(numSamples):
            minDist  = 100000.0  
            minIndex = 0  
            ## for each centroid  
            ## step 2: find the centroid who is closest
            for j in range(k):  
                distance = euclDistance(centroids[j, :], dataSet[i, :])  
                if distance < minDist:  
                    minDist  = distance  
                    minIndex = j  
              
            ## step 3: update its cluster
            if clusterAssment[i, 0] != minIndex:  
                clusterChanged = True  
                clusterAssment[i, :] = minIndex, minDist**2
  
        ## step 4: update centroids  
        for j in range(k):
            pointsInCluster = dataSet[nonzero(clusterAssment[:, 0].A == j)[0]]
            centroids[j, :] = mean(pointsInCluster, axis = 0)

    return clusterAssment[:,0]
    
kmeans_result = kmeans(iris_data, 3)
print("KMeans Iris",kmeans_result)
print(classification_report(iris_target, kmeans_result))

In [ ]:
##### IMPORTING LIBRARIES #####
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report

iris_target = iris.target

# K-Means Library
kmeans_iris = KMeans(n_clusters=3, init='k-means++', n_init=10, max_iter=300, tol=0.0001, precompute_distances='auto', 
                verbose=0, random_state=None, copy_x=True, n_jobs=1, algorithm='auto').fit_predict(iris)
print("KMeans Iris sklearn", kmeans_iris)
print(kmeans_iris.shape[0])
print(classification_report(iris_target, kmeans_iris))

# DBSCAN

In [14]:
# DBSCAN Function Implementation
class customDBSCAN:
    
    def __init__(self,data,e,minPts,distanceFunction):
        self.data = data
        self.e = e
        self.num_data = len(self.data)
        self.minPts = minPts
        self.labels = []
        self.cores = {}
        for x in range(len(self.data)):
            self.labels.append(-1)
        if distanceFunction == 'eucledian':
            self.distanceMatrix = calculateEucledianDistance(self.data)
        elif distanceFunction == 'manhattan':
            self.distanceMatrix = calculateManhattanDistance(self.data)
    def findCores(self):
        for i in range(self.num_data):
            temp_cluster = []
            for j in range(self.num_data):
                if (self.distanceMatrix[i][j] <= self.e and i != j):
                    temp_cluster.append(j)
            if(len(temp_cluster) >= self.minPts):
                self.cores[i] = temp_cluster
    
    def dfs_dbscan(self,dict_type_data,current_label):
        if(self.labels[dict_type_data] == -1):
            self.labels[dict_type_data] = current_label
            if dict_type_data in self.cores:
                for i in self.cores[dict_type_data]:
                    self.dfs_dbscan(i,current_label)
        
    def fit(self):
        label = -1
        self.findCores()
        for k,v in self.cores.items():
            if (self.labels[k] == -1):
                label+=1
            self.dfs_dbscan(k,label)

In [16]:
# MAIN
distanceFunction = 'eucledian'
epsilon = 1
minPts = 17

# OUR DBSCAN
db = customDBSCAN(iris,epsilon,minPts,distanceFunction)
db.fit()
print(db.labels)

# SCIKIT'S DBSCAN
from sklearn.cluster import DBSCAN
clustering = DBSCAN(eps=epsilon, min_samples=minPts).fit(iris)
print(clustering.labels_)

checkWithScikit(db.labels,clustering.labels_)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1 -1  1
  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1]
YAY


# AGGLOMERATIVE

In [3]:
#CUSTOM AGGLOMERATIVE
class customAgglomerative:
    def __init__(self,data,n_cluster,linkage='single',distanceFunction='eucledian'):
        self.data = data
        self.n_cluster = n_cluster
        
        if linkage == 'single':
            self.linkage = self.singleLinkage
        elif linkage == 'complete':
            self.linkage = self.completeLinkage
        elif linkage == 'average':
            self.linkage = self.averageLinkage
        elif linkage == 'average_group':
            self.linkage = self.averageGroupLinkage
        
        if distanceFunction == 'eucledian':
            self.distanceFunction = eucledianDistance
        elif distanceFunction == 'manhattan':
            self.distanceFunction = manhattanDistance
        
        self.distances = {}
        #clusters = list of tuples
        self.clusters = [(idx,)for idx in range(len(self.data))]
        #label of each data's cluster
        self.labels = []
        for i in range(len(self.data)):
            self.labels.append(i)
        
        
    def fit(self):
        
        while len(self.clusters)>self.n_cluster:
            a = 0
            b = 0
            clusterDistance = np.inf
            
            for i in range(len(self.clusters)):
                for j in range(i+1, len(self.clusters)):
                    temp_clusterDistance = self.getLinkageDistance(self.clusters[i],self.clusters[j])
                    if temp_clusterDistance < clusterDistance:
                        a,b,clusterDistance = i,j,temp_clusterDistance
                        
            self.clusters[a] = self.clusters[a] + self.clusters[b]
            del self.clusters[b]
            
        for i in range(len(self.clusters)):
            for j in self.clusters[i]:
                self.labels[j] = i
            
        return self.labels
            
        
    def getLinkageDistance(self,clust1,clust2):
        dist = self.distances.get((clust1,clust2))
        
        if dist == None:
            dist = self.distances.get((clust2,clust1))
        
        if dist == None:
            self.distances[(clust1,clust2)] = self.linkage(self.data,clust1,clust2,self.distanceFunction)
            dist = self.distances.get((clust1,clust2))
        
        return dist
        
            
    def singleLinkage(self,nodes,clust1,clust2,distance_function=eucledianDistance):
        dist = np.inf
        for i in clust1:
            for j in clust2:
                dist = min(dist,distance_function(nodes[i],nodes[j]))
        return dist
    
    def completeLinkage(self,nodes,clust1,clust2,distance_function=eucledianDistance):
        dist = -np.inf
        for i in clust1:
            for j in clust2:
                dist = max(dist,distance_function(nodes[i],nodes[j]))
        return dist
    
    def averageLinkage(self,nodes,clust1,clust2,distance_function=eucledianDistance):
        dist = 0
        for i in clust1:
            for j in clust2:
                dist += distance_function(nodes[i],nodes[j])
        return dist / (len(clust1)*len(clust2))
    
    def averageGroupLinkage(self,nodes,clust1,clust2,distance_function=eucledianDistance):
        dist = 0
        mean1 = []
        mean2 = []
        for i in clust1:
            for j in nodes[i]:
                mean1[i]+=j
            mean1[i]= mean1[i]/len(nodes)
        
        for i in clust2:
            for j in nodes[i]:
                mean2[i]+=j
            mean2[i]= mean2[i]/len(nodes)
        
        return distance_function(mean1,mean2)

In [9]:
from sklearn.cluster import AgglomerativeClustering

distanceFunction = 'eucledian'
linkage = 'complete'

scikitClustering = AgglomerativeClustering(linkage = 'complete',n_clusters = 4)
scikitClustering.fit(iris)

agl = customAgglomerative(iris,4,linkage,distanceFunction)

print(agl.fit())
print(scikitClustering.labels_)

checkWithScikit(agl.labels,scikitClustering.labels_)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 3, 1, 1, 3, 2, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 2 1 2 1 2 1 2 2 2 2 1 2 1 2 2 1 2 1 2 1 1
 1 1 1 1 1 2 2 2 2 1 2 1 1 1 2 2 2 1 2 2 2 2 2 1 2 2 1 1 3 1 1 3 2 3 1 3 1
 1 1 1 1 1 1 3 3 1 1 1 3 1 1 3 1 1 1 3 3 3 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]
YAY
